### ISSUE TITLE
System crash on tracker disconnect and reconnect

### ISSUE THREAD

**Issue by cosmic1** [antilatency/CustomEnvironmentExample#2]
While working with the standard environment system, alt trackers can be disconnected and reconnected to the system at anytime with no issue. When working with the custom environment system unity will crash with an access violation error in the antilatency.dll after reconnecting an alt tracker. If the tracker is not plugged in at start up the system will allow one reconnect. Disconnecting and reconnecting after that will cause the same error to appear.
[error.log](https://github.com/antilatency/CustomEnvironmentExample/files/5664194/error.log)

**Comment by psarev** [comment]
With the latest update to SDK 2.1.0, this issue was solved. https://github.com/antilatency/CustomEnvironmentExample/commit/6783775743dc2c104c874a3bc9139406af7d4704

**Comment by cosmic1** [comment]
Program still crashes when tracker is disconnected and reconnected even with SDK 2.1..
